### ISSUE TITLE
ERROR : ER_BLOB_KEY_WITHOUT_LENGTH: BLOB/TEXT columnused in key specification without a key length

### ISSUE THREAD

**Issue by moda20** [mickelindahl/waterline-table#1]
hey ! 

I am getting this error when using this package with mysql.
```
ER_BLOB_KEY_WITHOUT_LENGTH: BLOB/TEXT column 'UID' used in key specification without a key length
```
I tried to create a table using a `string` type column as a unique identifier, since that is transformed to type `TEXT` and that type doesn't have a specific size it can't be used as unique ID.

is there a way to specify this type of columns as `VARCHAR(128)` automatically ?

**Comment by mickelindahl** [comment]
Hi, I have never tried to use this with mysql.  With that said have you tried this?

let model = {
        identity: 'test',
        attributes: {
            id: {type: 'string', autoMigrations: {columnType: 'VARCHAR(128)'}},
        },
        primaryKey: 'id'
    };
